[package]
name = "cargo-xcframework"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
cargo_metadata = { version = "0.15", features = ["builder"] }
camino = "1.1"
dunce = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
yansi = "0.5"
fs-err = "2.9"
target-lexicon = { git = "https://github.com/akesson/target-lexicon.git", features = [
  "serde",
] }
# rustup-target = { git = "https://github.com/akesson/rustup-target.git" }
rustup-target = { path = "../rustup-target" }
lazy_static = "1.4"
dialoguer = "0.10"

[dev-dependencies]
tempfile = "3.3"
