[package]
name = "xcframework"
version = "0.1.0-alpha.2"
edition = "2021"
license = "MIT"
repository = "https://github.com/human-solutions/xcframework"
description = "Cargo plugin and library for building Apple XCFrameworks"
categories = ["development-tools::cargo-plugins", "development-tools::ffi"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
cargo_metadata = { version = "0.15", features = ["builder"] }
camino = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
yansi = "0.5"
fs-err = "2.9"
target-lexicon = { version = "0.12", features = ["serde_support"] }
rustup-configurator = "0.1"
lazy_static = "1.4"
dialoguer = "0.10"
zip-extensions = "0.6"
fs_extra = "1.2"

[dev-dependencies]
tempfile = "3.3"
markdown-includes = "0.1"
